# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your Name', max_length=200)),
                ('lastName', models.CharField(help_text='Your Lastname', max_length=200)),
                ('email', models.EmailField(help_text='Your Email', max_length=200)),
                ('passwd', models.CharField(default='9XKTQV', max_length=12)),
                ('createdAt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
