# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(help_text='can be Explorar,Ense\xf1ar,Entretener', max_length=2)),
                ('experience_type', models.CharField(help_text='what kind of experience would you like to guide.', max_length=100)),
                ('city', models.CharField(help_text='where experience will be held ?', max_length=100)),
                ('experience_about', models.CharField(help_text='what about the experience ?', max_length=200)),
                ('recluit_motive', models.CharField(help_text='motive to be part of manki', max_length=200)),
                ('recluit_name', models.CharField(help_text='your name', max_length=200)),
                ('recluit_email', models.EmailField(help_text='your email', max_length=100)),
                ('recluit_phone', models.CharField(help_text='your phone', max_length=20)),
                ('createdAt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
