# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='passwd',
            field=models.CharField(default='DSSZIY', max_length=12),
        ),
    ]
