# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guide', '0003_auto_20160604_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience_Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Experience name', max_length=200)),
                ('city', models.CharField(help_text='city', max_length=200)),
                ('detail', models.CharField(help_text='experience details', max_length=200)),
                ('conditions', models.CharField(help_text='conditions to take experience', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='princing', max_digits=5)),
                ('dates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience.Experience_Dates')),
                ('guide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='guide.Schema')),
            ],
        ),
    ]
